server:
  port: 7005
  servlet:
    context-path: /data
spring:
  application:
    name: evaluation-data-service
  datasource:
    # url: jdbc:mysql://127.0.0.1:8066/evaluation?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://mycat.tusdasa.net:8066/evaluation?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: consul.tusdasa.net
      port: 8500
      discovery:
        health-check-path: /data/actuator/health
        tags: management.context-path=/data/actuator
        prefer-ip-address: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss:SSS
    time-zone: GMT+8
#eureka:
#  client:
#    service-url:
#      defaultZone: http://tusdasa:8000/eureka/
mybatis:
  config-location: classpath:myBatisConfig.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"