server:
  port: 7014
  servlet:
    context-path: /thirdkpi
spring:
  application:
    name: evaluation-thirdkpi-service
  redis:
    host: redis.tusdasa.net
    port: 6379
    database: 7
  cache:
    redis:
      time-to-live: 604800
    type: redis
  datasource:
    url: jdbc:mysql://mycat.tusdasa.net:8066/evaluation?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: consul.tusdasa.net
      port: 8500
      discovery:
        health-check-path: /thirdkpi/actuator/health
        tags: management.context-path=/thirdkpi/actuator
        prefer-ip-address: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss:SSS
    time-zone: GMT+8
#eureka:
#  client:
#    service-url:
#      defaultZone: http://tusdasa:8000/eureka/
mybatis:
  config-location: classpath:myBatisConfig.xml
management:
#  metrics:
  #    export:
  #      prometheus:
  #        pushgateway:
  #          base-url: http://127.0.0.1:9090
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"