server:
  port: 7052
  servlet:
    context-path: /tevaluation
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss:SSS
    time-zone: GMT+8
  application:
    name: evaluation-teacher-evaluation
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: consul.tusdasa.net
      port: 8500
      discovery:
        health-check-path: /tevaluation/actuator/health
        tags: management.context-path=/tevaluation/actuator
        prefer-ip-address: true
  data:
    mongodb:
      uri: mongodb://mongodb.tusdasa.net:27017/evaluation
  rabbitmq:
    host: rabbitmq.tusdasa.net
    port: 5672
    username: evaluation
    password: 123456
    connection-timeout: 15000
    publisher-returns: true
    publisher-confirm-type: correlated
#eureka:
#  client:
#    service-url:
#      defaultZone: http://tusdasa:8000/eureka/
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"