server:
  port: 7085
  servlet:
    context-path: /calulation
spring:
  application:
    name: evaluation-calulation-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: consul.tusdasa.net
      port: 8500
      discovery:
        health-check-path: /calulation/actuator/health
        tags: management.context-path=/calulation/actuator
        prefer-ip-address: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss:SSS
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://mongodb.tusdasa.net:27017/evaluation
#eureka:
#  client:
#    service-url:
#      defaultZone: http://tusdasa:8000/eureka/
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"