server:
  port: 7004
  servlet:
    context-path: /course
spring:
  application:
    name: evaluation-course-service
  datasource:
    url: jdbc:mysql://mycat.tusdasa.net:8066/evaluation?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  redis:
    host: redis.tusdasa.net
    port: 6379
    database: 4
  cache:
    type: redis
    redis:
      time-to-live: 604800
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss:SSS
    time-zone: GMT+8
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: consul.tusdasa.net
      port: 8500
      discovery:
        health-check-path: /course/actuator/health
        tags: management.context-path=/course/actuator
        prefer-ip-address: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://tusdasa:8000/eureka/
mybatis:
  config-location: classpath:myBatisConfig.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"